[build]
# the documentation for the touchHLE crate is intended to include private items
# alas this isn't scoped to that crate!
rustdocflags = ["--document-private-items"]
[target.aarch64-linux-android]
rustflags = ["-C", "target-cpu=cortex-a55"]
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
